#' Compare .dosf (float) and .dos16 (integer) dosage matrices
#'
#' This function compares two dosage matrices stored in `bigmemory` format:
#' a floating-point dosage matrix (`.dosf`) and an integer dosage matrix (`.dos16`),
#' typically generated by multiplying `.dosf` values by 8192 and encoding missing values as 32768.
#'
#' It checks for consistency between the two formats, including discrepancies in both numeric values and missing values.
#' Detailed diagnostics are printed to the console to aid in manual inspection.
#'
#' @param prefix_float A character string. The file path prefix (without extension) for the `.dosf` bigmemory matrix.
#' @param prefix_int A character string. The file path prefix (without extension) for the `.dos16` bigmemory matrix.
#'
#' @return Invisibly returns the total number of mismatches (value mismatches + missing value mismatches). 
#' Also prints summary diagnostics to the console, including:
#' - Matrix extracts (original float, scaled float, integer)
#' - Positions of missing values
#' - Counts of mismatches
#' - Examples of mismatches if any
#'
#' @details
#' - The `.dosf` file is expected to contain floating-point dosage values.
#' - The `.dos16` file is expected to contain integer values in the range 0–8192, with 32768 used to encode missing values (`NaN` in the float version).
#' - Internally, the function scales the `.dosf` values by 8192 and rounds them to compare with the `.dos16` integers.
#'
#' @examples
#' vcf <- system.file("extdata", "example.vcf.gz", package = "readVCF")
#' prefix_int   <- tempfile("dosageint")
#' prefix_float <- tempfile("dosagefloat")
#' mk.dosage.file(vcf, prefix_int,   type = "integer")
#' mk.dosage.file(vcf, prefix_float, type = "float")
#' test.dosage.match(prefix_float, prefix_int)
#' 
test.dosage.match <- function(prefix_float, prefix_int) {
  library(bigmemory)

  # Attach bigmemory matrices
  dosf  <- attach.big.matrix(paste0(prefix_float, ".dosf.desc"))
  dos16 <- attach.big.matrix(paste0(prefix_int, ".dos16.desc"))

  n <- nrow(dosf)
  p <- ncol(dosf)

  # Copy contents into R matrices
  mat_float <- as.matrix(dosf[, ])
  mat_int   <- as.matrix(dos16[, ])

  # Scale float values (×8192 and rounded)
  scaled_float <- round(mat_float * 8192)

  # Fix incorrect signed values from .dos16
  mat_int[mat_int == -32768] <- 32768
  mat_int[mat_int < 0] <- NA_integer_

  # Display a small extract of the matrices
  rows <- 1:min(5, n)
  cols <- 1:min(5, p)
  cat("\nMatrice float (.dosf) [valeurs originales] :\n")
  print(mat_float[rows, cols])
  cat("\nMatrice float x 8192 [arrondie] :\n")
  print(scaled_float[rows, cols])
  cat("\nMatrice int (.dos16) [valeurs entières] :\n")
  print(mat_int[rows, cols])

  # Print positions of missing values
  cat("\nPosition des NaNs dans int (.dos16) :\n")
  print(which(is.na(mat_int), arr.ind = TRUE))
  cat("\nPosition des NaNs dans float (.dosf) :\n")
  print(which(is.na(mat_float), arr.ind = TRUE))

  # Compare missing values (TRUE where one is NA and the other isn't)
  nan_mismatch <- (is.na(mat_float) != (mat_int == 32768))

  # Compare numeric values (ignoring missing values)
  value_mismatch <- (scaled_float != mat_int) & !(mat_int == 32768)

  # Combine both types of mismatches
  diffs <- nan_mismatch | value_mismatch
  n_nan_mismatch <- sum(nan_mismatch, na.rm = TRUE)
  n_value_mismatch <- sum(value_mismatch, na.rm = TRUE)
  n_total_mismatch <- sum(diffs, na.rm = TRUE)
  
  # Print mismatch summaries
  cat("\nNombre de différences de NaN (float vs int) :", n_nan_mismatch, "\n")
  cat("Nombre de différences numériques :", n_value_mismatch, "\n")
  cat("Nombre total de différences :", n_total_mismatch, "\n")

  # Display mismatch examples
  if (n_total_mismatch > 0) {
    idx <- which(diffs, arr.ind = TRUE)
    cat("\nExemples de différences :\n")
    print(head(data.frame(
      row = idx[, 1],
      col = idx[, 2],
      float = mat_float[idx],
      float_scaled = scaled_float[idx],
      int = mat_int[idx],
      nan_mismatch = nan_mismatch[idx],
      value_mismatch = value_mismatch[idx]
    ), 10))
  }

  invisible(n_total_mismatch)
}