//header to test with test rep
/* Default config.h generated by Makefile */

#ifndef QUERY_REGIONS
#define QUERY_REGIONS

#ifndef _XOPEN_SOURCE
#define _XOPEN_SOURCE 600
#endif
#define HAVE_LIBBZ2 1
#define HAVE_LIBLZMA 1
#ifndef __APPLE__
#define HAVE_LZMA_H 1
#endif
#define HAVE_DRAND48 1


#include <zlib.h>
#include <stdio.h>
#include <string.h>
#include <strings.h>
#include <stdlib.h>
#include <unistd.h>
#include <inttypes.h>
#include <limits.h>
#include <stdint.h>
#include <fcntl.h>
#include <errno.h>
#include <time.h>
#include <sys/stat.h>
#include <assert.h>

//#include "hts.h"
#include "htslib/regidx.h"
#include "htslib/hts_defs.h"
#include "htslib/hts_log.h"
#include "htslib/bgzf.h"

//will have only an fname and a region in a str
#include "htslib/hfile.h" //to have hFILE type
#include "htslib/tbx.h"//to have tbx_conf_t

htsFile *hts_open_bis(const char *, const char *);
int generate_query_arguments(char *, char **, int, int);

#endif /*query_regions.h*/
