//query_regions.h taking place of config.h generated by ./configure
#include "query_regions.h"


    /**********************
     * OPENING INPUT FILE *
     **********************/


/**
 * Open an HTSlib File
 *
 *
 * @param fn   The file name of the HTSlib file to be opened.
 * @param mode The mode in which to open the file (in our case, always "r" for reading).
 * @param fmt  TO COMPLETE
 * @return     A pointer to the opened `htsFile`, or NULL if an error occurs.
 */

htsFile *hts_opening(const char *fn, const char *mode)
{
    char smode[101], *cp, *cp2, *uncomp = NULL;
    htsFile *fp = NULL;
    hFILE *hfile = NULL;
    char fmt_code = '\0';


    strncpy(smode, mode, 99);
    smode[99]=0;
    if ((cp = strchr(smode, ',')))//== 0, so false
        *cp = '\0';

    // Migrate format code (b or c) to the end of the smode buffer.
    for (cp2 = cp = smode; *cp; cp++) // initialise cp2 = 0
    {
        if (*cp == 'b')
            fmt_code = 'b';
        else if (*cp == 'c')
            fmt_code = 'c';
        else {//will enter here, puts cp2 back to 0
            *cp2++ = *cp;
            // Cache the uncompress flag 'u' pos if present
            if (!uncomp && (*cp == 'u')) {
                uncomp = cp2 - 1;
            }
        }
    }
    *cp2++ = fmt_code;
    *cp2++ = 0;


    hfile = hopen(fn, smode);
    if (hfile == NULL) goto error;

    fp = hts_hopen(hfile, fn, smode);
    if (fp == NULL) goto error;

    return fp;

error:
    fprintf(stderr, "Failed to open the file");

    if (hfile)
        hclose_abruptly(hfile);

    return NULL;
}