// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/readVCF.h"
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// openVCF_DS
Rcpp::XPtr<VCFReader<DS, double>> openVCF_DS(std::string filename, std::vector<std::string> regions);
RcppExport SEXP _readVCF_openVCF_DS(SEXP filenameSEXP, SEXP regionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type regions(regionsSEXP);
    rcpp_result_gen = Rcpp::wrap(openVCF_DS(filename, regions));
    return rcpp_result_gen;
END_RCPP
}
// getSamples_DS
Rcpp::CharacterVector getSamples_DS(Rcpp::XPtr<VCFReader<DS, double>> pin);
RcppExport SEXP _readVCF_getSamples_DS(SEXP pinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<VCFReader<DS, double>> >::type pin(pinSEXP);
    rcpp_result_gen = Rcpp::wrap(getSamples_DS(pin));
    return rcpp_result_gen;
END_RCPP
}
// getLine_DS
Rcpp::List getLine_DS(Rcpp::XPtr<VCFReader<DS, double>> pin);
RcppExport SEXP _readVCF_getLine_DS(SEXP pinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<VCFReader<DS, double>> >::type pin(pinSEXP);
    rcpp_result_gen = Rcpp::wrap(getLine_DS(pin));
    return rcpp_result_gen;
END_RCPP
}
// next_DS
bool next_DS(Rcpp::XPtr<VCFReader<DS, double>> pin);
RcppExport SEXP _readVCF_next_DS(SEXP pinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<VCFReader<DS, double>> >::type pin(pinSEXP);
    rcpp_result_gen = Rcpp::wrap(next_DS(pin));
    return rcpp_result_gen;
END_RCPP
}
// openVCF_GT
Rcpp::XPtr<VCFReader<GT, int>> openVCF_GT(std::string filename, std::vector<std::string> regions);
RcppExport SEXP _readVCF_openVCF_GT(SEXP filenameSEXP, SEXP regionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type regions(regionsSEXP);
    rcpp_result_gen = Rcpp::wrap(openVCF_GT(filename, regions));
    return rcpp_result_gen;
END_RCPP
}
// getSamples_GT
Rcpp::CharacterVector getSamples_GT(Rcpp::XPtr<VCFReader<GT, int>> pin);
RcppExport SEXP _readVCF_getSamples_GT(SEXP pinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<VCFReader<GT, int>> >::type pin(pinSEXP);
    rcpp_result_gen = Rcpp::wrap(getSamples_GT(pin));
    return rcpp_result_gen;
END_RCPP
}
// getLine_GT
Rcpp::List getLine_GT(Rcpp::XPtr<VCFReader<GT, int>> pin);
RcppExport SEXP _readVCF_getLine_GT(SEXP pinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<VCFReader<GT, int>> >::type pin(pinSEXP);
    rcpp_result_gen = Rcpp::wrap(getLine_GT(pin));
    return rcpp_result_gen;
END_RCPP
}
// next_GT
bool next_GT(Rcpp::XPtr<VCFReader<GT, int>> pin);
RcppExport SEXP _readVCF_next_GT(SEXP pinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<VCFReader<GT, int>> >::type pin(pinSEXP);
    rcpp_result_gen = Rcpp::wrap(next_GT(pin));
    return rcpp_result_gen;
END_RCPP
}
// readVCFgenotypes
SEXP readVCFgenotypes(std::string filename);
RcppExport SEXP _readVCF_readVCFgenotypes(SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    rcpp_result_gen = Rcpp::wrap(readVCFgenotypes(filename));
    return rcpp_result_gen;
END_RCPP
}
// readVCFgenotypes2
SEXP readVCFgenotypes2(std::string filename, std::vector<std::string> regions);
RcppExport SEXP _readVCF_readVCFgenotypes2(SEXP filenameSEXP, SEXP regionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type regions(regionsSEXP);
    rcpp_result_gen = Rcpp::wrap(readVCFgenotypes2(filename, regions));
    return rcpp_result_gen;
END_RCPP
}
// test_htsVCF
int test_htsVCF(std::string filename, std::vector<std::string> regions);
RcppExport SEXP _readVCF_test_htsVCF(SEXP filenameSEXP, SEXP regionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type regions(regionsSEXP);
    rcpp_result_gen = Rcpp::wrap(test_htsVCF(filename, regions));
    return rcpp_result_gen;
END_RCPP
}
// test1
int test1(std::string s);
RcppExport SEXP _readVCF_test1(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(test1(s));
    return rcpp_result_gen;
END_RCPP
}
// test2
int test2(std::string s, std::string tok);
RcppExport SEXP _readVCF_test2(SEXP sSEXP, SEXP tokSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type s(sSEXP);
    Rcpp::traits::input_parameter< std::string >::type tok(tokSEXP);
    rcpp_result_gen = Rcpp::wrap(test2(s, tok));
    return rcpp_result_gen;
END_RCPP
}
// test3
std::string test3(std::string s, int pos);
RcppExport SEXP _readVCF_test3(SEXP sSEXP, SEXP posSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type s(sSEXP);
    Rcpp::traits::input_parameter< int >::type pos(posSEXP);
    rcpp_result_gen = Rcpp::wrap(test3(s, pos));
    return rcpp_result_gen;
END_RCPP
}
// test4
Rcpp::IntegerVector test4();
RcppExport SEXP _readVCF_test4() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test4());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_readVCF_openVCF_DS", (DL_FUNC) &_readVCF_openVCF_DS, 2},
    {"_readVCF_getSamples_DS", (DL_FUNC) &_readVCF_getSamples_DS, 1},
    {"_readVCF_getLine_DS", (DL_FUNC) &_readVCF_getLine_DS, 1},
    {"_readVCF_next_DS", (DL_FUNC) &_readVCF_next_DS, 1},
    {"_readVCF_openVCF_GT", (DL_FUNC) &_readVCF_openVCF_GT, 2},
    {"_readVCF_getSamples_GT", (DL_FUNC) &_readVCF_getSamples_GT, 1},
    {"_readVCF_getLine_GT", (DL_FUNC) &_readVCF_getLine_GT, 1},
    {"_readVCF_next_GT", (DL_FUNC) &_readVCF_next_GT, 1},
    {"_readVCF_readVCFgenotypes", (DL_FUNC) &_readVCF_readVCFgenotypes, 1},
    {"_readVCF_readVCFgenotypes2", (DL_FUNC) &_readVCF_readVCFgenotypes2, 2},
    {"_readVCF_test_htsVCF", (DL_FUNC) &_readVCF_test_htsVCF, 2},
    {"_readVCF_test1", (DL_FUNC) &_readVCF_test1, 1},
    {"_readVCF_test2", (DL_FUNC) &_readVCF_test2, 2},
    {"_readVCF_test3", (DL_FUNC) &_readVCF_test3, 2},
    {"_readVCF_test4", (DL_FUNC) &_readVCF_test4, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_readVCF(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
