# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

VCFnext <- function(x) {
    .Call(`_readVCF_VCFnext`, x)
}

getChroms <- function(x) {
    .Call(`_readVCF_getChroms`, x)
}

getFormats <- function(x) {
    .Call(`_readVCF_getFormats`, x)
}

getLine <- function(x, field) {
    .Call(`_readVCF_getLine`, x, field)
}

getRegions <- function(x) {
    .Call(`_readVCF_getRegions`, x)
}

getSamples <- function(x) {
    .Call(`_readVCF_getSamples`, x)
}

openVCFregions <- function(filename, regions) {
    .Call(`_readVCF_openVCFregions`, filename, regions)
}

readVCFgenotypes <- function(filename) {
    .Call(`_readVCF_readVCFgenotypes`, filename)
}

readVCFgenotypes2 <- function(filename, regions) {
    .Call(`_readVCF_readVCFgenotypes2`, filename, regions)
}

test_htsVCF <- function(filename, regions) {
    .Call(`_readVCF_test_htsVCF`, filename, regions)
}

test1 <- function(s) {
    .Call(`_readVCF_test1`, s)
}

test2 <- function(s, tok) {
    .Call(`_readVCF_test2`, s, tok)
}

test3 <- function(s, pos) {
    .Call(`_readVCF_test3`, s, pos)
}

test4 <- function() {
    .Call(`_readVCF_test4`)
}

writeDosage <- function(filename, newfile_name, regions) {
    .Call(`_readVCF_writeDosage`, filename, newfile_name, regions)
}

