# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

VCFnext <- function(x) {
    .Call(`_readVCF_VCFnext`, x)
}

countVariants_ <- function(filename, regions) {
    .Call(`_readVCF_countVariants_`, filename, regions)
}

getChroms <- function(x) {
    .Call(`_readVCF_getChroms`, x)
}

getFormats <- function(x) {
    .Call(`_readVCF_getFormats`, x)
}

getLine <- function(x, field) {
    .Call(`_readVCF_getLine`, x, field)
}

getRegions_ <- function(x) {
    .Call(`_readVCF_getRegions_`, x)
}

getSamples <- function(x) {
    .Call(`_readVCF_getSamples`, x)
}

openVCFregions <- function(filename, regions) {
    .Call(`_readVCF_openVCFregions`, filename, regions)
}

readVCFgenotypes <- function(filename) {
    .Call(`_readVCF_readVCFgenotypes`, filename)
}

readVCFgenotypes2 <- function(filename, regions) {
    .Call(`_readVCF_readVCFgenotypes2`, filename, regions)
}

test_htsVCF <- function(filename, regions) {
    .Call(`_readVCF_test_htsVCF`, filename, regions)
}

test1 <- function(s) {
    .Call(`_readVCF_test1`, s)
}

test2 <- function(s, tok) {
    .Call(`_readVCF_test2`, s, tok)
}

test3 <- function(s, pos) {
    .Call(`_readVCF_test3`, s, pos)
}

test4 <- function() {
    .Call(`_readVCF_test4`)
}

writeDosage <- function(filename, newfile_name, regions) {
    .Call(`_readVCF_writeDosage`, filename, newfile_name, regions)
}

#' Write integer dosage matrix (.dos16) from VCF file
#'
#' This function reads a VCF file with DS (dosage) format and generates:
#' - A `.dos16` binary file containing scaled integer dosage values (uint16_t)
#' - A `.bim` file with SNP metadata (chr, id, pos, ref, alt)
#'
#' Dosage values are multiplied by 8192 and rounded to the nearest integer.
#' Missing values are encoded as 32768.
#'
#' @param filename The path to the input VCF file.
#' @param newfile_name The output file prefix (without extension).
#' @param regions A list of regions to read from the VCF.
#' @return A list with:
#'   - `samples`: vector of sample IDs
#'   - `nbSNPs`: number of SNPs written
#'
#' @throws std::runtime_error if input is invalid or output files exist already.
#'
#' @details The `.dos16` file is a binary matrix of dimension (number of SNPs × number of samples)
#'          stored in row-major order (each SNP as a row).
#'
#' @note This function appends no data. It will fail if the target output file already exists.
#'
writeDosageInteger <- function(filename, newfile_name, regions) {
    .Call(`_readVCF_writeDosageInteger`, filename, newfile_name, regions)
}

