#' Compare .dosf (float) and .dos16 (integer) dosage matrices
#'
#' This function compares two dosage matrices stored in `bigmemory` format:
#' a floating-point dosage matrix (`.dosf`) and an integer dosage matrix (`.dos16`)
#' typically generated by multiplying `.dosf` values by 8192 and encoding missing values as 32768.
#'
#' It checks for consistency between the two formats, reports differences (excluding missing values),
#' and displays concrete examples for manual verification.
#'
#' @param prefix_float Character string. The prefix (file path without extension) of the `.dosf` bigmemory matrix.
#' @param prefix_int Character string. The prefix (file path without extension) of the `.dos16` bigmemory matrix.
#'
#' @return Invisibly returns the number of differences found (excluding NA/32768). Outputs detailed
#' diagnostics to the console, including:
#' - Matrix comparisons (original, scaled, integer)
#' - Summary of discrepancies
#' - Manual inspection examples (e.g., SNP with missing values, SNP #1862)
#'
#' @details
#' - The `.dosf` file is expected to contain floating-point dosage values.
#' - The `.dos16` file is expected to contain integer values in the range 0–8192, with 32768 used to encode missing values (`NaN` in the float version).
#' - Internally, the function scales the `.dosf` values by 8192 and rounds them to compare with the `.dos16` integers.
#'
#' @examples
#' \dontrun{
#' test.dosage.match("data/sample", "data/sample")
#' }
#' 
#' @export
test.dosage.match <- function(prefix_float, prefix_int) {
  library(bigmemory)
  
  # Attaching bigmemory arrays
  dosf  <- attach.big.matrix(paste0(prefix_float, ".dosf.desc"))
  dos16 <- attach.big.matrix(paste0(prefix_int, ".dos16.desc"))
  
  n <- nrow(dosf)
  p <- ncol(dosf)
  
  # R matrix conversion
  mat_float <- matrix(NA_real_, n, p)
  mat_int   <- matrix(NA_integer_, n, p)
  
  for (i in seq_len(n)) {
    mat_float[i, ] <- dosf[i, ]
    mat_int[i, ]   <- dos16[i, ]
  }
  
  # Displays the value of line 90, column 1862
  cat("\n Vérification manuelle : valeur ligne 90, SNP 1862 (.dosf):\n")
  print(mat_float[90, 1862])
  
  scaled_float <- round(mat_float * 8192)
  
  # Correction for negative int16 values
  mat_int[mat_int == -32768] <- 32768  # rare case (signed bit interpreted)
  mat_int[mat_int < 0] <- NA_integer_ # security
  
  
  
  # Display an extract
  rows <- 1:min(5, n)
  cols <- 1:min(5, p)
  cat("\n Matrice float (.dosf) [valeurs originales] :\n")
  print(mat_float[rows, cols])
  cat("\n Matrice float x 8192 [arrondie] :\n")
  print(scaled_float[rows, cols])
  cat("\n Matrice int (.dos16) [valeurs entières] :\n")
  print(mat_int[rows, cols])
  
  # Search for an SNP with encoded NaN (32768)
  snp_with_nan <- which(colSums(mat_int == 32768) > 0)
  if (length(snp_with_nan) > 0) {
    snp_id <- snp_with_nan[1]
    cat("\n Exemple de SNP contenant au moins un NaN (./.) :\n")
    cat(" → SNP numéro :", snp_id, "\n")
    
    df_nan <- data.frame(
      float = mat_float[, snp_id],
      scaled = scaled_float[, snp_id],
      int = mat_int[, snp_id]
    )
    print(df_nan)
    cat("\n → Indices avec NaN encodé (32768) :\n")
    print(which(mat_int[, snp_id] == 32768))
  }
  
  # Comparison of values (excluding NA)
  is_na <- (mat_int == 32768)
  diffs <- (scaled_float != mat_int) & !is_na
  n_diffs <- sum(diffs, na.rm = TRUE)
  
  cat("\n Nombre de différences (hors NA) :", n_diffs, "\n")
  
  if (n_diffs > 0) {
    idx <- which(diffs, arr.ind = TRUE)
    cat("\n Exemples de différences :\n")
    print(head(data.frame(
      row = idx[, 1],
      col = idx[, 2],
      float = mat_float[idx],
      float_scaled = scaled_float[idx],
      int = mat_int[idx]
    ), 10))
  }
  
  # Explicit verification
  cat("\n Vérification explicite de la présence de 32768 dans mat_int :\n")
  print(any(mat_int == 32768, na.rm = TRUE))
  
  # Example: display of the first SNP with 32768
  has_nan <- apply(mat_int == 32768, 2, function(x) any(x, na.rm = TRUE))
  snp_with_nan <- which(has_nan)
  
  if (length(snp_with_nan) > 0) {
    snp_id <- snp_with_nan[1]
    cat("\n Exemple de SNP contenant au moins un NaN (./.) :\n")
    cat(" → SNP numéro :", snp_id, "\n")
    df_nan <- data.frame(
      float = mat_float[, snp_id],
      scaled = scaled_float[, snp_id],
      int = mat_int[, snp_id]
    )
    print(df_nan)
    cat("\n → Lignes avec NaN encodé (32768) :\n")
    print(which(mat_int[, snp_id] == 32768))
  }
  
  # Targeted display: SNP rs1578411 (#1862)
  snp_1862 <- 1862
  if (snp_1862 <= p) {
    cat("\n Contenu de la colonne correspondant au SNP #1862 (rs1578411, pos 20:17178434) :\n")
    df_1862 <- data.frame(
      float  = mat_float[, snp_1862],
      scaled = scaled_float[, snp_1862],
      int    = mat_int[, snp_1862]
    )
    print(df_1862)
    cat("\n → Indices avec NaN encodé (32768) pour SNP 1862 :\n")
    print(which(mat_int[, snp_1862] == 32768))
  }
  
  invisible(n_diffs)
}